<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYNhqYXF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYNhqYXF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYNhqYXF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYNhqYXF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYNhqYXF\App_KernelDevDebugContainer([
    'container.build_hash' => 'YNhqYXF',
    'container.build_id' => '587d3544',
    'container.build_time' => 1639750916,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYNhqYXF');
